USE [master]
GO

/****** Object:  Database [trialrun1]    Script Date: 29/5/2020 1:17:21 PM ******/
CREATE DATABASE [trialrun1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'trialrun1', FILENAME = N'D:\rdsdbdata\DATA\trialrun1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'trialrun1_log', FILENAME = N'D:\rdsdbdata\DATA\trialrun1_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [trialrun1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [trialrun1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [trialrun1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [trialrun1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [trialrun1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [trialrun1] SET ARITHABORT OFF 
GO

ALTER DATABASE [trialrun1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [trialrun1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [trialrun1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [trialrun1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [trialrun1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [trialrun1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [trialrun1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [trialrun1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [trialrun1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [trialrun1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [trialrun1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [trialrun1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [trialrun1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [trialrun1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [trialrun1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [trialrun1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [trialrun1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [trialrun1] SET RECOVERY FULL 
GO

ALTER DATABASE [trialrun1] SET  MULTI_USER 
GO

ALTER DATABASE [trialrun1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [trialrun1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [trialrun1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [trialrun1] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [trialrun1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [trialrun1] SET QUERY_STORE = OFF
GO

ALTER DATABASE [trialrun1] SET  READ_WRITE 
GO


